name: checkbox-ce-oem Snap daily cross-builds
permissions:
  contents: read
on:
  workflow_dispatch:
    inputs:
      store_upload:
        description: 'Should the workflow upload to the store?'
        default: false
        required: false
        type: boolean
  workflow_call:
    inputs:
      store_upload:
        description: 'Should the workflow upload to the store?'
        default: false
        required: false
        type: boolean
    secrets:
      SNAPCRAFT7_CREDS:
        required: true

jobs:
  snap-frontend:
    strategy:
      fail-fast: false
      matrix:
        type: [classic, uc]
        release: [20, 22, 24]
        arch: [armhf, amd64, arm64]
        exclude:
          # other confs built natively in checkbox-daily-native-builds.yaml
          - release: 20
            arch: amd64
          - release: 20
            arch: arm64
          - release: 22
            arch: amd64
          - release: 22
            arch: arm64
          - release: 24
            arch: amd64
          - release: 24
            arch: arm64
    runs-on: ubuntu-latest
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    name: Frontend ${{ matrix.type }}${{ matrix.release }} (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Copy over the common files for series ${{ matrix.release }}
        run: |
          cd contrib/checkbox-ce-oem/checkbox-ce-oem-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./prepare.sh series_${{ matrix.type }}${{ matrix.release }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

      - id: snap_build
        name: Build (retries on fail)
        uses: Wandalen/wretry.action@71a909ebf09f3ffdc6f42a17bd54ecb43481da49
        with:
          attempt_limit: 5
          action: canonical/snapcraft-multiarch-action@v1
          with: |
            architecture: ${{ matrix.arch }}
            path: contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_${{ matrix.type }}${{ matrix.release }}

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        name: Upload logs on failure
        if: failure()
        with:
          name: frontend-build-log-${{ matrix.type }}${{ matrix.release }}-${{ matrix.arch }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_${{ matrix.type }}${{ matrix.release }}/checkbox*.txt

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        name: Upload the snaps as artefacts
        with:
          name: frontend_snaps_${{ matrix.type }}${{ matrix.release }}_${{matrix.arch}}.snap
          path: ${{ steps.snap_build.outputs.snap }}

      - name: Publish track
        # this is done this way because the store doesn't allow the same artifact to be uploaded twice
        if: inputs.store_upload && (matrix.release != 24 || matrix.type != 'classic')
        uses: canonical/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
        with:
          snap: ${{ steps.snap_build.outputs.snap }}
          # channel is ucXX for uc snaps and XX.04 for classic snaps
          release: ${{ matrix.type == 'uc' && format('uc{0}', matrix.release) || format('{0}.04', matrix.release) }}/edge

      - name: Publish track + latest
        if: inputs.store_upload && matrix.release == 24 && matrix.type == 'classic'
        uses: canonical/action-publish@214b86e5ca036ead1668c79afb81e550e6c54d40
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
        with:
          snap: ${{ steps.snap_build.outputs.snap }}
          # classic 24.04 is published to latest/edge as well
          release: 24.04/edge,latest/edge
