name: Beta version of checkbox-core-snap
run-name: Beta version of checkbox-core-snap ${{ github.ref_name }}

on:
  push:
    tags:
        - "v*"
  workflow_dispatch:

jobs:
  snap:
    strategy:
      fail-fast: false
      matrix:
        releases: [16, 18, 20, 22]
    runs-on: self-hosted
    env:
      SERIES: series${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
    name: Checkbox core snap for series${{ matrix.releases }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Copy over the common files for series${{ matrix.releases }}
        run: |
          cd checkbox-core-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./prepare.sh $SERIES
      - name: add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/provider/launchpad/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/provider/launchpad/credentials
          git config --global user.email "robot@lists.canonical.com"
          git config --global user.name "Certification bot"
      - uses: snapcore/action-build@v1
        id: snapcraft
        with:
          path: checkbox-core-snap/series${{ matrix.releases }}
          snapcraft-channel: 7.x/stable
          snapcraft-args: remote-build --build-on amd64,arm64,armhf,i386 --launchpad-accept-public-upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: snapcraft-log-series${{ matrix.releases }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            checkbox-core-snap/series${{ matrix.releases }}/checkbox*.txt
      - uses: actions/upload-artifact@v3
        with:
          name: series${{ matrix.releases }}
          path: checkbox-core-snap/series${{ matrix.releases }}/*.snap
      - name: Check that snapcraft built the expected amount of snaps
        run: |
          NB_SNAPS=$(find checkbox-core-snap/series${{ matrix.releases }} -maxdepth 1 -type f -name *.snap | wc -l)
          # Expecting 3 snaps for checkbox20 and checkbox22 (amd64, armhf, arm64)
          # and 4 snaps for checkbox16 and checkbox18 (i386, amd64, armhf, arm64)
          if [ ${{ matrix.releases }} == "16" ] || [ ${{ matrix.releases }} == "18" ]
          then
            if [ ${NB_SNAPS} != "4" ]
            then
              echo "Error: Snapcraft should have produced 4 snaps, found ${NB_SNAPS} instead."
                exit 1
            fi
          else
            if [ ${NB_SNAPS} != "3" ]
            then
              echo "Error: Snapcraft should have produced 3 snaps, found ${NB_SNAPS} instead."
              exit 1
            fi
          fi
      - name: Upload checkbox core snaps to the store
        run: |
          for snap in checkbox-core-snap/series${{ matrix.releases }}/*.snap
          do
            echo "Uploading $snap..."
            snapcraft upload $snap --release beta
          done

  changelog:
    runs-on: self-hosted
    name: checkbox-snap changelog (${{ github.ref_name }})
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create changelog
        run: |
          git config --global user.email "robot@canonical.com"
          git config --global user.name "Devices Certification Bot"
          for project in checkbox-core-snap checkbox-ng checkbox-support providers/*
          do
            log=$(git log --no-merges --pretty='format:+ %s' $(git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/tags/checkbox-core-snap-v* | tail -n 2 | head -n 1)...${{ github.ref_name }} -- "$project")
            if [[ ! -z $log ]]
            then
              echo $project:
              echo "$log"
              echo
            fi
          done > changelog
      - name: Archive changelog
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: changelog
