name: checkbox-ce-oem snap edge build
permissions:
  contents: read
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      SNAPCRAFT7_CREDS:
        required: true

jobs:
  snap:
    strategy:
      fail-fast: false
      matrix:
        type: [classic, uc]
        releases: [20, 22, 24]
    runs-on:
      group: "Canonical self-hosted runners"
      labels:
        - self-hosted
        - linux
        - jammy
        - large
        - X64
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    env:
      SERIES: series_${{ matrix.type }}${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
      # snapcraft remote-build will create a repository with the name decided by the --build-id arg
      # URL to this repo echoed below to help debug builds (does not change if the workflow is re-run)
      # as the run_id will not change
      SNAPCRAFT_BUILDER_ID: checkbox-${{ matrix.type }}${{ matrix.releases }}-${{ github.run_id }}
    name: Frontend ${{ matrix.type }}${{ matrix.releases }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/provider/launchpad/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/provider/launchpad/credentials
          git config --global user.email "robot@lists.canonical.com"
          git config --global user.name "Certification bot"
      - name: Print Launchpad build repository
        run: |
          echo "Building at: https://git.launchpad.net/~ce-certification-qa/+snap/$SNAPCRAFT_BUILDER_ID"
      - uses: Wandalen/wretry.action@71a909ebf09f3ffdc6f42a17bd54ecb43481da49
        name: Building the snaps
        timeout-minutes: 600 # 10hours
        with:
          action: Hook25/action-build@707dce252c4f367b6c1afe61ed577f7413cf7912
          attempt_delay: 600000 # 10min
          attempt_limit: 5
          with: |
            path: contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_${{ matrix.type }}${{ matrix.releases }}
            snapcraft-channel: 7.x/stable
            snapcraft-args: remote-build --build-for amd64,arm64,armhf --launchpad-accept-public-upload --build-id $SNAPCRAFT_BUILDER_ID
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        name: Upload logs on failure
        if: failure()
        with:
          name: ce-oem-build-log-${{ matrix.type }}${{ matrix.releases }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_${{ matrix.type }}${{ matrix.releases }}/checkbox*.txt
      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
        name: Upload the snaps as artefacts
        with:
          name: ce_oem_snap${{ matrix.type }}${{ matrix.releases }}
          path: contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_${{ matrix.type }}${{ matrix.releases }}/*.snap
      - uses: Wandalen/wretry.action@71a909ebf09f3ffdc6f42a17bd54ecb43481da49
        name: Upload the snaps to the store
        timeout-minutes: 600 # 10hours
        with:
          attempt_delay: 600000 # 10min
          attempt_limit: 10
          command: |
            for snap in contrib/checkbox-ce-oem/checkbox-ce-oem-snap/series_${{ matrix.type }}${{ matrix.releases }}/*.snap ; \
            do \
              echo "Uploading $snap..." ; \
              if [ ${{ matrix.type }} = 'classic' ]; then \
                snapcraft upload $snap --release ${{ matrix.releases }}.04/edge ; \
                fi \
              else \
                if [ ${{ matrix.releases }} = '24' ]; then \
                  snapcraft upload $snap --release ${{ matrix.type }}${{ matrix.releases }}/edge,latest/edge ; \
                else \
                  snapcraft upload $snap --release ${{ matrix.type }}${{ matrix.releases }}/edge ; \
                fi \
              fi ; \
            done
