name: Fling a checkbox job with Testflinger

on:
    push:
        branches: [test-action-fling-test]
    workflow_dispatch:

jobs:
  checkbox-canary-test:
    runs-on: [self-hosted, testflinger]
    strategy:
      fail-fast: false
      matrix:
        include:
          - checkbox_runtime: checkbox16
            data_source: "distro: xenial"
            checkbox_track: uc16
            arch: amd64
            queue: hp-elitebook-850-g7-notebook-pc

    steps:
    - name: Checkout checkbox monorepo
      uses: actions/checkout@v4

    - name: Create job
      id: create-job
      shell: bash
      run: |
        OUTPUT_PATH=${{ github.workspace }}/job.yaml
        cat << JOB_EOF > $OUTPUT_PATH
        job_queue : ${{ matrix.queue }}
        global_timeout: 3600
        output_timeout: 1800
        provision_data:
          ${{ matrix.data_source }}
        test_data:
          test_cmds: |
            echo Running on \$DEVICE_IP
            sudo add-apt-repository -y ppa:checkbox-dev/edge
            sudo apt-get -qq update
            sudo DEBIAN_FRONTEND=noninteractive apt-get -qq install -y checkbox-ng
            PYTHONUNBUFFERED=1 checkbox-cli --version 
            EXITCODE=\$?
        JOB_EOF
        echo "job=$OUTPUT_PATH" >> $GITHUB_OUTPUT

    - name: Verify job
      shell: bash
      run:
        cat ${{ steps.create-job.outputs.job }}

    - name: Submit job
      uses: canonical/testflinger/.github/actions/submit@CERTTF-327-github-action-submit
      with:
        dry-run: false
        poll: true
        job: ${{ steps.create-job.outputs.job }}
