name: Checkbox Snapcraft8 builds

on:
  workflow_dispatch:
  workflow_call:

jobs:
  snap_runtime_native:
    strategy:
      fail-fast: false
      matrix:
        releases: [18, 20, 22, 24]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            tag: X64
          - arch: arm64
            tag: ARM64
          - releases: 18
            snapcraft_version: 7.x
          - releases: 20
            snapcraft_version: 7.x
          - releases: 22
            snapcraft_version: 8.x
          - releases: 24
            snapcraft_version: 8.x
    runs-on:
      group: "Canonical self-hosted runners"
      labels:
        - self-hosted
        - linux
        - jammy
        - large
        - ${{ matrix.tag }}
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    env:
      SERIES: series${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
    name: Runtime ${{ matrix.releases }}  (${{matrix.arch}})
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy over the common files for series ${{ matrix.releases }}
        run: |
          cd checkbox-core-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./prepare.sh $SERIES
      - name: Add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/launchpad-credentials
          git config --global user.email "robot@lists.canonical.com"
          git config --global user.name "Certification bot"
      - uses: Wandalen/wretry.action@v3.4.0_js_action
        name: Build the snap
        timeout-minutes: 600 # 10hours
        with:
          action: snapcore/action-build@v1.3.0
          attempt_delay: 600000 # 10min
          attempt_limit: 5
          with: |
            path: checkbox-core-snap/series${{ matrix.releases }}
            snapcraft-channel: ${{ matrix.snapcraft_version }}/stable
      - uses: actions/upload-artifact@v4
        name: Upload logs on failure
        if: failure()
        with:
          name: snapcraft-log-series${{ matrix.releases }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            checkbox-core-snap/series${{ matrix.releases }}/checkbox*.txt
      - uses: actions/upload-artifact@v4
        name: Upload the snap as artifact
        with:
          name: checkbox${{ matrix.releases }}_${{ matrix.arch }}
          path: checkbox-core-snap/series${{ matrix.releases }}/*.snap

  snap_frontend_native:
    strategy:
      fail-fast: false
      matrix:
        type: [classic, uc]
        releases: [18, 20, 22, 24]
        arch: [amd64, arm64]
        include:
          - arch: amd64
            tag: X64
          - arch: arm64
            tag: ARM64
          - releases: 18
            snapcraft_version: 7.x
          - releases: 20
            snapcraft_version: 7.x
          - releases: 22
            snapcraft_version: 8.x
          - releases: 24
            snapcraft_version: 8.x
    runs-on:
      group: "Canonical self-hosted runners"
      labels:
        - self-hosted
        - linux
        - jammy
        - large
        - ${{ matrix.tag }}
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    env:
      SERIES: series_${{ matrix.type }}${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
    name: Frontend ${{ matrix.type }}${{ matrix.releases }} (${{matrix.arch}})
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy over the common files for series ${{ matrix.type }}${{ matrix.releases }}
        run: |
          cd checkbox-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./prepare_${{ matrix.type }}.sh $SERIES
      - name: Add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/launchpad-credentials
          git config --global user.email "robot@lists.canonical.com"
          git config --global user.name "Certification bot"
      - uses: Wandalen/wretry.action@v3.4.0_js_action
        name: Building the snaps
        timeout-minutes: 600 # 10hours
        with:
          action: snapcore/action-build@v1.3.0
          attempt_delay: 600000 # 10min
          attempt_limit: 5
          with: |
            path: checkbox-snap/series_${{ matrix.type }}${{ matrix.releases }}
            snapcraft-channel: ${{ matrix.snapcraft_version }}/stable
      - uses: actions/upload-artifact@v4
        name: Upload logs on failure
        if: failure()
        with:
          name: snapcraft-log-series-${{ matrix.type }}${{ matrix.releases }}${{ matrix.arch }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            checkbox-snap/series_${{ matrix.type }}${{ matrix.releases }}/checkbox*.txt
      - uses: actions/upload-artifact@v4
        name: Upload the snaps as artefacts
        with:
          name: series_${{ matrix.type }}${{ matrix.releases }}${{ matrix.arch }}
          path: checkbox-snap/series_${{ matrix.type }}${{ matrix.releases }}/*.snap

  snap_runtime_remote_build:
    strategy:
      fail-fast: false
      matrix:
        releases: [22, 24]
        arch: [armhf]
    runs-on: [self-hosted, linux, jammy, large]
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    env:
      SERIES: series${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
      # snapcraft remote-build will create a repository with the name decided by the --build-id arg
      # URL to this repo echoed below to help debug builds (does not change if the workflow is re-run)
      SNAPCRAFT_BUILDER_ID: checkbox${{ matrix.releases }}-${{ matrix.arch }}-${{ github.run_id }}
    name: Runtime ${{ matrix.releases }} (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/launchpad-credentials
          git config --global user.email "robot@lists.canonical.com"
          git config --global user.name "Certification bot"
      - name: Copy over the common files for series ${{ matrix.releases }}
        run: |
          cd checkbox-core-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./snapcraft8_prepare.sh $SERIES
          git add ..
          git commit -m "Prepared build"
      - name: Print Launchpad build repository
        run: |
          echo "Building at: https://git.launchpad.net/~ce-certification-qa/+snap/$SNAPCRAFT_BUILDER_ID"
      - uses: Wandalen/wretry.action@v3.4.0_js_action
        name: Build the snap
        timeout-minutes: 600 # 10hours
        with:
          action: snapcore/action-build@v1.3.0
          attempt_delay: 600000 # 10min
          attempt_limit: 5
          with: |
            snapcraft-channel: 8.0/stable
            snapcraft-args: remote-build --build-for ${{ matrix.arch }} --launchpad-accept-public-upload --build-id "checkbox${{ matrix.releases }}-${{ matrix.arch }}-${{ github.run_id }}" --launchpad-timeout=36000
      - uses: actions/upload-artifact@v4
        name: Upload logs on failure
        if: failure()
        with:
          name: runtime-build-log-${{ matrix.releases }}-${{ matrix.arch }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            checkbox*.txt
      - uses: actions/upload-artifact@v4
        name: Upload the snap as artifact
        with:
          name: runtime_snap${{ matrix.releases }}_${{ matrix.arch }}
          path: "checkbox*.snap"

  snap_frontend_remote_build:
    strategy:
      fail-fast: false
      matrix:
        type: [classic, uc]
        releases: [22, 24]
        arch: [armhf]
    runs-on: [self-hosted, linux, jammy, large]
    timeout-minutes: 1200 #20h, this will timeout sooner due to inner timeouts
    env:
      SERIES: series_${{ matrix.type }}${{ matrix.releases }}
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT7_CREDS }}
      # snapcraft remote-build will create a repository with the name decided by the --build-id arg
      # URL to this repo echoed below to help debug builds (does not change if the workflow is re-run)
      # as the run_id will not change
      SNAPCRAFT_BUILDER_ID: checkbox-${{ matrix.type }}${{ matrix.releases }}-${{ github.run_id }}
    name: Frontend ${{ matrix.type }}${{ matrix.releases }} (${{ matrix.arch }})
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Add LP credentials
        run: |
          mkdir -p ~/.local/share/snapcraft/
          echo '${{ secrets.LP_CREDS }}' > ~/.local/share/snapcraft/launchpad-credentials
          git config --global user.email "robot@lists.canonical.com"
          git config --global user.name "Certification bot"
      - name: Copy over the common files for series ${{ matrix.type }}${{ matrix.releases }}
        run: |
          cd checkbox-snap/
          sudo apt update && sudo apt install -qq -y python3-setuptools-scm
          ./snapcraft8_prepare_${{ matrix.type }}.sh $SERIES
          git add ..
          git commit -m "Prepared build"
      - name: Print Launchpad build repository
        run: |
          echo "Building at: https://git.launchpad.net/~ce-certification-qa/+snap/$SNAPCRAFT_BUILDER_ID"
      - uses: Wandalen/wretry.action/main@v3.4.0_js_action
        name: Building the snaps
        timeout-minutes: 600 # 10hours
        with:
          action: snapcore/action-build@v1.3.0
          attempt_delay: 600000 # 10min
          attempt_limit: 5
          with: |
            snapcraft-channel: 8.0/stable
            snapcraft-args: remote-build --build-for ${{ matrix.arch }} --launchpad-accept-public-upload --build-id "checkbox-${{ matrix.type }}${{ matrix.releases }}-${{ github.run_id }}" --launchpad-timeout=36000
      - uses: actions/upload-artifact@v4
        name: Upload logs on failure
        if: failure()
        with:
          name: frontend-build-log-${{ matrix.type }}${{ matrix.releases }}
          path: |
            /home/runner/.cache/snapcraft/log/
            /home/runner/.local/state/snapcraft/log/
            checkbox*.txt
      - uses: actions/upload-artifact@v4
        name: Upload the snaps as artefacts
        with:
          name: frontend_snaps${{ matrix.type }}${{ matrix.releases }}
          path: "checkbox*.snap"
